-- AlterTable
ALTER TABLE "User" ADD COLUMN     "bronzeBadges" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "goldBadges" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "silverBadges" INTEGER NOT NULL DEFAULT 0;
